# Installation script for a fake (i386) OpenWRT Blue Box
#
# To test out your changes:
#
#   1. Install Docker as per the instructions at
#      https://docs.docker.com/installation/, or just run the
#      develop_noc.sh script and follow the instructions
#   2. cd to the directory of this file
#   3. docker build -t epflsti/blueboxfake:dev .
#      docker run -ti epflsti/blueboxfake:dev /bin/bash

FROM solarkennedy/openwrt
MAINTAINER Dominique Quatravaux <dominique.quatravaux@epfl.ch>

